---
- name: systemd reload
  command: systemctl daemon-reload
  become: yes
- name: restart otemot
  service:
    name: otemot
    state: restarted
  become: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
