image: archlinux
packages:
  - nodejs
  - npm
  - openssl
  - elixir
sources:
  - git+https://github.com/tometoproject/tometo
tasks:
  - lint: |
      cd tometo
      mix local.hex --force
      cd aph; mix deps.get; cd ..
      script/lint
