image: archlinux
packages:
  - nodejs
  - npm
sources:
  - hg+https://callie.marisa.cloud/tometo/tometo
tasks:
  - setup: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2019-09-11
      source $HOME/.cargo/env
      rustup --version
      rustc --version
      cargo --version
  - lint: |
      source $HOME/.cargo/env
      cd tometo
      script/lint
