image: archlinux
sources:
  - hg+https://callie.marisa.cloud/tometo/tometo
tasks:
  - setup: |
      cd tometo
      script/cisetup
  - lint: |
      source $HOME/.cargo/env
      cd tometo
      script/lint
