---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: archlinux/base
    commands:
      - pacman -Syy
      - pacman -S nodejs npm python espeak ffmpeg postgresql openssl
      - script/cisetup
      - source $HOME/.cargo/env
      - script/lint
