image: node:buster

stages:
  - test

lint tometo:
  stage: "test"
  script:
    - npm install
    - npm run lint

lint otemot:
  stage: "test"
  cache:
    key: otemot-lint
    paths:
      - out/
  before_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2019-07-18
    - source $HOME/.cargo/env
    - rustc --version
  script:
    - cargo check --target-dir out/
