image: node:lts-alpine

stages:
  - test

lint tometo:
  stage: "test"
  script:
    - npm install
    - npm run lint

lint otemot:
  stage: "test"
  before_script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - curl https://sh.rustup.rs -sSf | sh -s -- -y  --default-toolchain stable
    - rustc --version
  script:
    - cargo check
