image: node:lts-alpine

before_script:
  - apk add curl
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

stages:
  - test

lint tometo:
  stage: "test"
  script:
    - npm install
    - npm run lint

lint otemot:
  stage: "test"
  script:
    - cargo check
