image: node:lts-alpine

stages:
  - test

lint tometo:
  stage: "test"
  script:
    - npm install
    - npm run lint

lint otemot:
  stage: "test"
  before_script:
    - apk add curl rust cargo
    - rustc --version
  script:
    - cargo check
