image: alpine:edge

stages:
  - test

lint tometo:
  stage: "test"
  before_script:
    - apk update
    - apk add nodejs npm
  script:
    - npm install
    - npm run lint

lint otemot:
  stage: "test"
  cache:
    key: otemot-lint
    paths: out/

  before_script:
    - apk update
    - apk add curl rust cargo openssl-dev postgresql-dev
    - rustc --version
  script:
    - cargo check --target-dir out/
