## This playbook installs Tometo along with all of its dependencies onto the Vagrant guest machine.

- hosts: all
  roles:
  - common

- hosts: all
  roles:
  - git

- hosts: all
  roles:
  - postgres

- hosts: all
  roles:
  - elixir
  tags:
  - install

- hosts: all
  roles:
  - node

- hosts: all
  roles:
  - python

- hosts: all
  roles:
  - espeak

- hosts: all
  roles:
  - ffmpeg

- hosts: all
  roles:
  - elixir
  tags:
  - setup

- hosts: all
  roles:
  - tometo