[package]
name = "otemot"
version = "0.1.0"
authors = ["marisa <marisa@mokou.zone>"]
edition = "2018"

[dependencies]
actix-web = { version = "1.0" }
actix = "0.8"
actix-files = "0.1"
actix-cors = "0.1"
actix-rt = "0.2"
diesel = { version = "1.3.2", features = ["postgres", "uuid", "serde_json", "r2d2", "chrono"] }
chrono = { version = "0.4.6", features = ["serde"] }
uuid = { version = "0.6.5", features = ["serde", "v4"] }
r2d2 = "0.8"
serde = "1.0.90"
serde_derive = "1.0.90"
bcrypt = "0.4.0"
md5 = "0.6.1"
ring = "0.14.6"
serde_json = "1.0.39"
futures = "0.1.26"
env_logger = "0.6.1"
sentry = "0.15.5"
sentry-actix = "0.15.5"
derive_more = "0.15.0"
actix-identity = "0.1.0"
jsonwebtoken = "6.0.1"
sensitive_words = "1.0.2"
config = "0.9.3"
