- name: Run localsetup script
  shell:
    cmd: /home/vagrant/tometo/script/localsetup

- name: Create dev.exs using Ansible variables
  template:
    src: dev.exs.j2
    dest: /vagrant/config/dev.exs

- name: Run database setup
  shell:
    chdir: /vagrant/
    cmd: mix ecto.setup
