- name: Run localsetup script
  shell:
    cmd: /home/vagrant/tometo/script/localsetup

- name: Create config.exs using Ansible variables
  template:
    src: config.exs.j2
    dest: /vagrant/config/config.exs

- name: Run database setup
  shell:
    chdir: /vagrant/
    cmd: mix ecto.setup
