- name: Run localsetup script
  shell:
    cmd: /home/vagrant/tometo/script/localsetup

- name: Check if config.exs exists
  stat: path=/vagrant/aph/config/config.exs
  register: config

- name: Create config.exs using Ansible variables if it doesn't exist
  template:
    src: config.exs.j2
    dest: /vagrant/aph/config/config.exs
  when: not config.stat.exists

- name: Run database setup
  shell:
    chdir: /vagrant/aph/ 
    cmd: mix ecto.setup
