---
- name: Checkout from Git
  git: repo=git@marisa.cloud:tometo/tometo.git dest={{ checkout_dir }} version={{ checkout_branch }}
- name: Copy config file
  template: src=config.j2 dest={{ checkout_dir }}/config.toml
- name: Install npm dependencies
  npm:
    path: {{ checkout_dir }}
- name: Set up databases
  shell: source ~/.profile && diesel setup
  args:
    chdir: {{ checkout_dir }}/otemot
    executable: /bin/bash
- name: Copy nginx file
  template: src=nginx.j2 dest=/etc/nginx/conf.d/otemot.conf
  become: yes
  args:
    force: no
  notify:
    - restart nginx
- name: Copy systemd file
  template: src=systemd.j2 dest=/etc/systemd/system/otemot.service
  become: yes
  notify:
    - systemd reload
- name: Compile
  shell: source ~/.profile && cargo build --release
  args:
    chdir: {{ checkout_dir }}
    executable: /bin/bash
  notify:
    - restart otemot
