- name: Install PostgreSQL
  become: true
  apt:
    name: "postgresql"
    state: present

- name: Install postgresql-contrib
  become: true
  apt:
    name: "postgresql-contrib"
    state: present

- name: Install postgresql-contrib
  become: true
  apt:
    name: "postgresql-contrib"
    state: present

- name: Install libpq-dev
  become: true
  apt:
    name: "libpq-dev"
    state: present