- name: Install PostgreSQL
  become: true
  apt:
    name: "postgresql"
    state: present

- name: Install postgresql-contrib
  become: true
  apt:
    name: "postgresql-contrib"
    state: present

- name: Install postgresql-contrib
  become: true
  apt:
    name: "postgresql-contrib"
    state: present

- name: Install libpq-dev
  become: true
  apt:
    name: "libpq-dev"
    state: present

- name: Install psycopg2
  become: true
  apt:
    name: "python-psycopg2"
    state: present

# TODO: refactor this
- name: Include Tometo vars
  include_vars:
    file: ../../tometo/vars/main.yml

- name: Create Postgres user for Tometo
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ tometo_database_username }}"
    password: "{{ tometo_database_password }}"
    role_attr_flags: "CREATEDB"
    
- name: Create Postgres database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ tometo_database_name }}"

- name: Give the new Postgres user database privileges
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ tometo_database_name }}"
    role: "{{ tometo_database_username }}"
    objs: ALL_IN_SCHEMA
    privs: ALL