---
- name: Checkout from Git
  git: repo={{ tometo_repo }} dest=/var/www/{{ checkout_dir }} version={{ checkout_branch }}
- name: Install npm packages
  npm:
    path: /var/www/{{ checkout_dir }}
- name: Copy .env file
  template: src=env.j2 dest=/var/www/{{ checkout_dir }}/.env
- name: Run build script
  command: chdir=/var/www/{{ checkout_dir }} npm run build
- name: Copy nginx config
  become: yes
  template: src=nginx.j2 dest=/etc/nginx/conf.d/tometo.conf
  args:
    force: no
  notify:
    - restart nginx
